title: Maël Guesdon
description: Auteur, chercheur - Publications, recherches et créations
theme: jekyll-theme-minimal
lang: fr
author: Maël Guesdon
url: "https://maelguesdon.fr"
show_excerpts: false
